# Defaults
export SHELL=/bin/zsh
export EDITOR=nano

#ZSH_THEME https://github.com/bhilburn/powerlevel9k
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE="awesome-powerline"

plugins=(git gradle adb colored-man-pages jump alias-tips zsh-syntax-highlighting sublime atom)

DEFAULT_USER="Esteve"

source $ZSH/oh-my-zsh.sh
source /usr/local/bin/aws_zsh_completer.sh

#DIR
POWERLEVEL9K_DIR_PATH_SEPARATOR=' $(print_icon "LEFT_SUBSEGMENT_SEPARATOR") '
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

#VCS
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='cyan'

#BATTERY
#WARNING: DON'T USE IF YOUR COMPUTER HAS NO BATTERY!!
POWERLEVEL9K_BATTERY_VERBOSE=false
POWERLEVEL9K_BATTERY_ICON=''
POWERLEVEL9K_BATTERY_CHARGING='yellow'
POWERLEVEL9K_BATTERY_CHARGED='green'
POWERLEVEL9K_BATTERY_DISCONNECTED='$DEFAULT_COLOR'
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='15'
POWERLEVEL9K_BATTERY_LOW_COLOR='black'
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='red'
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='blue'

#COMMAND EXECUTION TIME
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='yellow'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'

#PROMPTS
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time context dir vcs)
#WARNING: REMOVE battery IF YOUR COMPUTER HAS NO BATTERY!
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status rbenv command_execution_time battery)

POWERLEVEL9K_STATUS_VERBOSE=true
